from GenerateStructureElectrical import *
from GenerateStructureMechanical import *
from GenerateStructureMooring import *
#from GenerateStructureFirmware import *
from GenerateStructureTest import *
from GenerateStructurePhotos import *
from GenerateStructureCruise import *
from GenerateStructureDocumentation import *
from GenerateStructurePurchases import *
from GenerateStructureSubsystem import *
